### ISSUE TITLE
Colab, no buttons in fullscreen landscape mode on mobile

### ISSUE THREAD

**Issue by simzer** [vizzuhq/vizzu-story-js#18]
@petervidos Please link an example, where this problem can be seen.

**Comment by petervidos** [comment]
Itt egy példa, ami egy Colabben lévő notebookból van, ahol a View output full screen opciót használtam.
Ez a notebook:
https://colab.research.google.com/drive/1euV8sihG6j2f0ePoMpl4I30gNhR42NBk?usp=sharing
![Uploading Screenshot_20220929-133555_Chrome.jpg…]()

Notebookból generált html-ben nem jelentkezik a hiba.
Link: https://vizzuhq.github.io/ipyvizzu-story/examples/demo/ipyvizzu-story_example.html

![Screenshot_20220929-133707_Chrome](https://user-images.githubusercontent.com/10341970/193021614-265dab96-e6b6-458f-a923-2532948f64ed.jpg)

**Comment by simzer** [comment]
@veghdev According to Peter's comment it's more like an ipyvizzu-story problem. Could you take a look please?

**Comment by veghdev** [comment]
@simzer In colab fullscreen the buttons are not fit in the screen. If I rotate and select the button, then rotate it back, it seems that the button box is still there, but the button image is under the display
