### ISSUE TITLE
development: use new keyframe support of vizzu + add slider

### ISSUE THREAD

**Issue by simzer** [vizzuhq/vizzu-story-js#24]
Vizzu now supports multiple animations in a single animation call:
```javascript
chart.animate(
 [
  {
    target: { data, chart, style },
    options: animOptions
  },
  ...
],
animopts)
```
Note: this feature is not released yet, but available from commit https://github.com/vizzuhq/vizzu-lib/commit/3b73f2fa93e69c782285353b11d2e94fc6a3e2e5
Available online here: https://vizzu-lib-main-sha.storage.googleapis.com/lib-3b73f2f/vizzu.js

The benefit of using this to pass slide phases together in one animate() call is that vizzu will consider this as a single animation.
This way adding a slider which can seek through all the phases becomes more simple.

**Comment by simzer** [comment]
Also, with this change: https://github.com/vizzuhq/vizzu-lib/pull/150/commits/03653adeaee1e3da208f3edaf6bdb123d5d4d011, the whole animation (containing start, end, intermediate charts + anim options) can be stored and restored. Using this feature could simplify the current code. 
Vizzu version hosted here: https://vizzu-lib-main-sha.storage.googleapis.com/lib-03653ad/vizzu.js
Example code repeating the previous animation:
```javascript
chart.animate(...).then(chart => chart.animate(chart.animation.store()))
```

**Comment by dyuri** [comment]
@simzer I've removed the sub-slide concept and switched to keyframes - see my PR. Looks fine here.
I'd add the slider in a second step, but if this part works then it should be quite straightforward.

**Comment by simzer** [comment]
The animation control interface is changed. The animate method returns a promise, which still resolves when the animation is finished, but it does not incorporate the control methods. Instead, it contains another promise called 'activated', which resolves to the controller object when the animation starts.
See https://lib.vizzuhq.com/0.7/tutorial/animation_control_keyframes/

**Comment by simzer** [comment]
@dyuri The problem seems to be that while vizzu-story calls vizzu.animate with the list of keyframes now, it still stores only the end chart:
```javascript
await this.vizzu.animate(animParams);
chartSteps.push(this.vizzu.store());
```
To be able to work correctly, it should store the whole animation:
```javascript
let animation = this.vizzu.animate(animParams);
let control = await animation.activated;
chartSteps.push(control.store());
await animation;
```

**Comment by simzer** [comment]
After discussion with @dyuri: 
Fix needed in vizzu lib, to allow reverse playing of stored animation. see https://github.com/vizzuhq/vizzu-lib/issues/166

**Comment by simzer** [comment]
https://github.com/vizzuhq/vizzu-lib/issues/166 fixed

Animation can be played in reverse using these options:
```javascript
chart.animate(anim, { position: 1, direction: 'reverse' });
```
Working example: https://jsfiddle.net/simzer/tfmjsunr/19/
pre-release url: https://vizzu-lib-main-sha.storage.googleapis.com/lib-66a2735/vizzu.js
