### ISSUE TITLE
should prevent PgUp, PgDn keypress events to pass to parent elements.

### ISSUE THREAD

**Issue by veghdev** [vizzuhq/vizzu-story-js#43]
environment issues: Colab, Deepnote, PgUp, PgDn buttons scroll the notebook even after the chart is clicked 

PgUp, PgDn buttons scroll the notebook even after the chart is clicked (separated from the issues vizzuhq/ipyvizzu-story#2 vizzuhq/ipyvizzu-story#3)

**Comment by dovicsin** [comment]
it is also true for the home and end buttons
